# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'youtubePlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for youtubePlayer
  pod "XCDYouTubeKit", "~> 2.12"

end
